name: Project proposal form
description: Please use this form to propose your project for review. The decision of the review will be communicated to you. 
title: "[Proposal]: "
labels: ["Ops: Proposal"]


body:
  - type: input
    id: project-name
    attributes:
      label: Project Name
      description: Enter the name of the project
      placeholder: project name...
    validations:
      required: true
#### Submitter name ####
  - type: input
    id: submitter-name
    attributes:
      label: Submitter name
      description: Enter the name of the submitter in Firstname, Lastname format
      placeholder: Firstname, Lastname
    validations:
      required: true
#### submitter Github ID ####  
  - type: input
    id: identifying-information
    attributes:
      label: Submitter Github ID
      description: Enter the Github ID of the submitter in @username format
      placeholder: Username
    validations:
      required: true
#### project vision #### 
  - type: textarea
    id: project-vision
    attributes:
      label: Project Vision
      description: Please tell us briefly about the vision you have for this project.
      placeholder: Type in your vision here
      #value: my vision
    validations:
      required: true

#### OKRs ####   
  - type: textarea
    id: okr
    attributes:
      label: Objectives and Key results
      description: Objectives tells you where to go and Key Results tells you what results you need to reach the objective 
      placeholder: Please inlcude both objectives and key results...
      #value: my vision
    validations:
      required: true

#### Project vertical #### 
  - type: checkboxes
    id: vertical
    attributes:
      label: Which vertical within SCRF does your project fall under?
      description: Who are the target audience for this project? Select all that applies.
      options:
        - label: Unsure
        - label: Operations
        - label: Discovery
        - label: Engagement
  
#### Alignment with scrf #### 
  - type: textarea
    id: alignment
    attributes:
      label: Alignment with SCRFs Vision and Mission #"[Vision and Mission](https://github.com/smartcontractresearchforum/docs)" #change this later
      description: How does your  project align with SCRFs vision and Mission?
      placeholder: Alignment with SCRF...
    validations:
      required: true

#### deliverables ####         
  - type: textarea
    id: deliverables
    attributes:
      label: Deliverables
      description: What would be the deliverables of the project once it is completed?
      placeholder: Deliverables...
    validations:
      required: true

#### Project team #### 
  - type: textarea
    id: project-team
    attributes:
      label: Project team
      description: Who would be involved in this project? Please list all collaborators and use the format shown below in the text box.
      placeholder: |
        Project Lead: Firstname, Lastname ; email@example.com ; availability: 15h/week
        Other Collaborators: 
        1. Firstname, Lastname ; email@example.com ; availability: 15h/week
        2. Firstname, Lastname ; email@example.com ; availability: 15h/week...
    validations:
      required: true

#### MVP ####
  - type: dropdown
    id: mvp
    attributes:
      label:  Is MVP Possible?
      description: Is a Minimum Viable Project possible with the project?
      options:
        - ✔️
        - ❌
    validations:
      required: true    

  - type: input
    id: duration
    attributes:
      label: Duration
      description: What is the expected duration of the project?
      placeholder: Please denote in hours...
    validations:
      required: true
      
#### Target Audience ####
  - type: checkboxes
    id: target-audience
    attributes:
      label: Target audience 
      description: Who are the target audience for this project? Select all that applies.
      options:
        - label: SCRF Internal
        - label: Academics
        - label: Industry
        - label: Other
        
#### Link to G-Doc ####         
  - type: textarea
    id: G-Doc
    attributes:
      label: G-Doc
      description: Please give a link to the proposal Google Doc.
      placeholder: link...
    validations:
      required: true
