name: Project proposal form Rev1
description: place holder 
title: "[Proposal]: "
labels: ["Ops: Proposal"]

body:
  - type: input
    id: project-name
    attributes:
      label: Project Name
      description: Enter the name of the project
      placeholder: project name...
    validations:
      required: true
#### Submitter name ####
  - type: input
    id: submitter-name
    attributes:
      label: Submitter name
      description: Enter the name of the submitter in Firstname, Lastname format
      placeholder: Firstname, Lastname
    validations:
      required: true
#### submitter Github ID ####  
  - type: input
    id: identifying-information
    attributes:
      label: Submitter Github ID
      description: Enter the Github ID of the submitter in @username format
      placeholder: Username
    validations:
      required: true
#### project vision #### 
  - type: textarea
    id: project-vision
    attributes:
      label: Project Vision
      description: Please tell us briefly about the vision you have for this project.
      placeholder: Type in your vision here
      #value: my vision
    validations:
      required: true
