name: New Issue to Project Board

on:
  issues:
    types: [opened]

jobs:
  add-to-help-desk:    
    runs-on: ubuntu-latest    
    steps:    
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/smartcontractresearchforum/projects/40
          github-token: ${{ secrets.OPERATIONS_ISSUES_PB_PAT }}